// Code generated by internal/gen from herdr's API schema. DO NOT EDIT.
// Source: `herdr api schema --json`, protocol 17.

package herdrapi

import "encoding/json"

// Protocol is the herdr socket protocol version these types were generated
// from. Compare it against a newer `herdr api schema --json` to see whether
// regenerating is worthwhile.
const Protocol = 17

type AgentInfo struct {
	Agent                  *string           `json:"agent,omitempty"`
	AgentSession           *AgentSessionInfo `json:"agent_session,omitempty"`
	AgentStatus            AgentStatus       `json:"agent_status"`
	CWD                    *string           `json:"cwd,omitempty"`
	DisplayAgent           *string           `json:"display_agent,omitempty"`
	Focused                bool              `json:"focused"`
	ForegroundCWD          *string           `json:"foreground_cwd,omitempty"`
	InteractiveReady       *bool             `json:"interactive_ready,omitempty"`
	LaunchPending          *bool             `json:"launch_pending,omitempty"`
	Name                   *string           `json:"name,omitempty"`
	PaneID                 string            `json:"pane_id"`
	Revision               uint64            `json:"revision"`
	ScreenDetectionSkipped *bool             `json:"screen_detection_skipped,omitempty"`
	StateChangeSeq         *uint64           `json:"state_change_seq,omitempty"`
	StateLabels            map[string]string `json:"state_labels,omitempty"`
	TabID                  string            `json:"tab_id"`
	TerminalID             string            `json:"terminal_id"`
	TerminalTitle          *string           `json:"terminal_title,omitempty"`
	TerminalTitleStripped  *string           `json:"terminal_title_stripped,omitempty"`
	Title                  *string           `json:"title,omitempty"`
	Tokens                 map[string]string `json:"tokens,omitempty"`
	WorkspaceID            string            `json:"workspace_id"`
}

type AgentManifestInfo struct {
	ActiveVersion                *string `json:"active_version,omitempty"`
	Agent                        string  `json:"agent"`
	CachedRemoteVersion          *string `json:"cached_remote_version,omitempty"`
	LocalOverrideShadowingRemote bool    `json:"local_override_shadowing_remote"`
	RemoteLastCheckedUnix        *uint64 `json:"remote_last_checked_unix,omitempty"`
	RemoteUpdateError            *string `json:"remote_update_error,omitempty"`
	RemoteUpdateResult           *string `json:"remote_update_result,omitempty"`
	Source                       string  `json:"source"`
	SourceKind                   string  `json:"source_kind"`
	Warning                      *string `json:"warning,omitempty"`
}

type AgentSessionInfo struct {
	Agent  string              `json:"agent"`
	Kind   AgentSessionRefKind `json:"kind"`
	Source string              `json:"source"`
	Value  string              `json:"value"`
}

type AgentSessionRefKind string

const (
	AgentSessionRefKindID   AgentSessionRefKind = "id"
	AgentSessionRefKindPath AgentSessionRefKind = "path"
)

type AgentStatus string

const (
	AgentStatusIdle    AgentStatus = "idle"
	AgentStatusWorking AgentStatus = "working"
	AgentStatusBlocked AgentStatus = "blocked"
	AgentStatusDone    AgentStatus = "done"
	AgentStatusUnknown AgentStatus = "unknown"
)

type ClientWindowTitleReason string

const (
	ClientWindowTitleReasonSet                ClientWindowTitleReason = "set"
	ClientWindowTitleReasonCleared            ClientWindowTitleReason = "cleared"
	ClientWindowTitleReasonNoForegroundClient ClientWindowTitleReason = "no_foreground_client"
)

type ConfigReloadStatus string

const (
	ConfigReloadStatusApplied ConfigReloadStatus = "applied"
	ConfigReloadStatusPartial ConfigReloadStatus = "partial"
	ConfigReloadStatusFailed  ConfigReloadStatus = "failed"
)

// EventData is a tagged union; decode it into the matching variant.
type EventData = json.RawMessage

// WorkspaceCreatedEvent is the "workspace_created" variant of EventData.
type WorkspaceCreatedEvent struct {
	Type      string        `json:"type"`
	Workspace WorkspaceInfo `json:"workspace"`
}

// TagWorkspaceCreatedEvent is the EventData discriminator for WorkspaceCreatedEvent.
const TagWorkspaceCreatedEvent = "workspace_created"

// WorkspaceUpdatedEvent is the "workspace_updated" variant of EventData.
type WorkspaceUpdatedEvent struct {
	Type      string        `json:"type"`
	Workspace WorkspaceInfo `json:"workspace"`
}

// TagWorkspaceUpdatedEvent is the EventData discriminator for WorkspaceUpdatedEvent.
const TagWorkspaceUpdatedEvent = "workspace_updated"

// WorkspaceMetadataUpdatedEvent is the "workspace_metadata_updated" variant of EventData.
type WorkspaceMetadataUpdatedEvent struct {
	Type      string        `json:"type"`
	Workspace WorkspaceInfo `json:"workspace"`
}

// TagWorkspaceMetadataUpdatedEvent is the EventData discriminator for WorkspaceMetadataUpdatedEvent.
const TagWorkspaceMetadataUpdatedEvent = "workspace_metadata_updated"

// WorkspaceClosedEvent is the "workspace_closed" variant of EventData.
type WorkspaceClosedEvent struct {
	Type        string         `json:"type"`
	Workspace   *WorkspaceInfo `json:"workspace,omitempty"`
	WorkspaceID string         `json:"workspace_id"`
}

// TagWorkspaceClosedEvent is the EventData discriminator for WorkspaceClosedEvent.
const TagWorkspaceClosedEvent = "workspace_closed"

// WorkspaceRenamedEvent is the "workspace_renamed" variant of EventData.
type WorkspaceRenamedEvent struct {
	Label       string `json:"label"`
	Type        string `json:"type"`
	WorkspaceID string `json:"workspace_id"`
}

// TagWorkspaceRenamedEvent is the EventData discriminator for WorkspaceRenamedEvent.
const TagWorkspaceRenamedEvent = "workspace_renamed"

// WorkspaceMovedEvent is the "workspace_moved" variant of EventData.
type WorkspaceMovedEvent struct {
	InsertIndex uint64          `json:"insert_index"`
	Type        string          `json:"type"`
	WorkspaceID string          `json:"workspace_id"`
	Workspaces  []WorkspaceInfo `json:"workspaces"`
}

// TagWorkspaceMovedEvent is the EventData discriminator for WorkspaceMovedEvent.
const TagWorkspaceMovedEvent = "workspace_moved"

// WorkspaceFocusedEvent is the "workspace_focused" variant of EventData.
type WorkspaceFocusedEvent struct {
	Type        string `json:"type"`
	WorkspaceID string `json:"workspace_id"`
}

// TagWorkspaceFocusedEvent is the EventData discriminator for WorkspaceFocusedEvent.
const TagWorkspaceFocusedEvent = "workspace_focused"

// WorktreeCreatedEvent is the "worktree_created" variant of EventData.
type WorktreeCreatedEvent struct {
	Type      string        `json:"type"`
	Workspace WorkspaceInfo `json:"workspace"`
	Worktree  WorktreeInfo  `json:"worktree"`
}

// TagWorktreeCreatedEvent is the EventData discriminator for WorktreeCreatedEvent.
const TagWorktreeCreatedEvent = "worktree_created"

// WorktreeOpenedEvent is the "worktree_opened" variant of EventData.
type WorktreeOpenedEvent struct {
	AlreadyOpen bool          `json:"already_open"`
	Type        string        `json:"type"`
	Workspace   WorkspaceInfo `json:"workspace"`
	Worktree    WorktreeInfo  `json:"worktree"`
}

// TagWorktreeOpenedEvent is the EventData discriminator for WorktreeOpenedEvent.
const TagWorktreeOpenedEvent = "worktree_opened"

// WorktreeRemovedEvent is the "worktree_removed" variant of EventData.
type WorktreeRemovedEvent struct {
	Forced      bool           `json:"forced"`
	Type        string         `json:"type"`
	Workspace   *WorkspaceInfo `json:"workspace,omitempty"`
	WorkspaceID string         `json:"workspace_id"`
	Worktree    WorktreeInfo   `json:"worktree"`
}

// TagWorktreeRemovedEvent is the EventData discriminator for WorktreeRemovedEvent.
const TagWorktreeRemovedEvent = "worktree_removed"

// TabCreatedEvent is the "tab_created" variant of EventData.
type TabCreatedEvent struct {
	Tab  TabInfo `json:"tab"`
	Type string  `json:"type"`
}

// TagTabCreatedEvent is the EventData discriminator for TabCreatedEvent.
const TagTabCreatedEvent = "tab_created"

// TabClosedEvent is the "tab_closed" variant of EventData.
type TabClosedEvent struct {
	TabID       string `json:"tab_id"`
	Type        string `json:"type"`
	WorkspaceID string `json:"workspace_id"`
}

// TagTabClosedEvent is the EventData discriminator for TabClosedEvent.
const TagTabClosedEvent = "tab_closed"

// TabRenamedEvent is the "tab_renamed" variant of EventData.
type TabRenamedEvent struct {
	Label       string `json:"label"`
	TabID       string `json:"tab_id"`
	Type        string `json:"type"`
	WorkspaceID string `json:"workspace_id"`
}

// TagTabRenamedEvent is the EventData discriminator for TabRenamedEvent.
const TagTabRenamedEvent = "tab_renamed"

// TabMovedEvent is the "tab_moved" variant of EventData.
type TabMovedEvent struct {
	InsertIndex uint64    `json:"insert_index"`
	TabID       string    `json:"tab_id"`
	Tabs        []TabInfo `json:"tabs"`
	Type        string    `json:"type"`
	WorkspaceID string    `json:"workspace_id"`
}

// TagTabMovedEvent is the EventData discriminator for TabMovedEvent.
const TagTabMovedEvent = "tab_moved"

// TabFocusedEvent is the "tab_focused" variant of EventData.
type TabFocusedEvent struct {
	TabID       string `json:"tab_id"`
	Type        string `json:"type"`
	WorkspaceID string `json:"workspace_id"`
}

// TagTabFocusedEvent is the EventData discriminator for TabFocusedEvent.
const TagTabFocusedEvent = "tab_focused"

// PaneCreatedEvent is the "pane_created" variant of EventData.
type PaneCreatedEvent struct {
	Pane PaneInfo `json:"pane"`
	Type string   `json:"type"`
}

// TagPaneCreatedEvent is the EventData discriminator for PaneCreatedEvent.
const TagPaneCreatedEvent = "pane_created"

// PaneClosedEvent is the "pane_closed" variant of EventData.
type PaneClosedEvent struct {
	PaneID      string `json:"pane_id"`
	Type        string `json:"type"`
	WorkspaceID string `json:"workspace_id"`
}

// TagPaneClosedEvent is the EventData discriminator for PaneClosedEvent.
const TagPaneClosedEvent = "pane_closed"

// PaneUpdatedEvent is the "pane_updated" variant of EventData.
type PaneUpdatedEvent struct {
	Pane PaneInfo `json:"pane"`
	Type string   `json:"type"`
}

// TagPaneUpdatedEvent is the EventData discriminator for PaneUpdatedEvent.
const TagPaneUpdatedEvent = "pane_updated"

// PaneFocusedEvent is the "pane_focused" variant of EventData.
type PaneFocusedEvent struct {
	PaneID      string `json:"pane_id"`
	Type        string `json:"type"`
	WorkspaceID string `json:"workspace_id"`
}

// TagPaneFocusedEvent is the EventData discriminator for PaneFocusedEvent.
const TagPaneFocusedEvent = "pane_focused"

// PaneMovedEvent is the "pane_moved" variant of EventData.
type PaneMovedEvent struct {
	ClosedTabID         *string        `json:"closed_tab_id,omitempty"`
	ClosedWorkspaceID   *string        `json:"closed_workspace_id,omitempty"`
	CreatedTab          *TabInfo       `json:"created_tab,omitempty"`
	CreatedWorkspace    *WorkspaceInfo `json:"created_workspace,omitempty"`
	Pane                PaneInfo       `json:"pane"`
	PreviousPaneID      string         `json:"previous_pane_id"`
	PreviousTabID       string         `json:"previous_tab_id"`
	PreviousWorkspaceID string         `json:"previous_workspace_id"`
	Type                string         `json:"type"`
}

// TagPaneMovedEvent is the EventData discriminator for PaneMovedEvent.
const TagPaneMovedEvent = "pane_moved"

// PaneOutputChangedEvent is the "pane_output_changed" variant of EventData.
type PaneOutputChangedEvent struct {
	PaneID      string `json:"pane_id"`
	Revision    uint64 `json:"revision"`
	Type        string `json:"type"`
	WorkspaceID string `json:"workspace_id"`
}

// TagPaneOutputChangedEvent is the EventData discriminator for PaneOutputChangedEvent.
const TagPaneOutputChangedEvent = "pane_output_changed"

// PaneExitedEvent is the "pane_exited" variant of EventData.
type PaneExitedEvent struct {
	PaneID      string `json:"pane_id"`
	Type        string `json:"type"`
	WorkspaceID string `json:"workspace_id"`
}

// TagPaneExitedEvent is the EventData discriminator for PaneExitedEvent.
const TagPaneExitedEvent = "pane_exited"

// PaneAgentDetectedEvent is the "pane_agent_detected" variant of EventData.
type PaneAgentDetectedEvent struct {
	Agent       *string      `json:"agent,omitempty"`
	FinalStatus *AgentStatus `json:"final_status,omitempty"`
	PaneID      string       `json:"pane_id"`
	Released    *bool        `json:"released,omitempty"`
	Type        string       `json:"type"`
	WorkspaceID string       `json:"workspace_id"`
}

// TagPaneAgentDetectedEvent is the EventData discriminator for PaneAgentDetectedEvent.
const TagPaneAgentDetectedEvent = "pane_agent_detected"

// PaneAgentStatusChangedEvent is the "pane_agent_status_changed" variant of EventData.
type PaneAgentStatusChangedEvent struct {
	Agent        *string           `json:"agent,omitempty"`
	AgentStatus  AgentStatus       `json:"agent_status"`
	DisplayAgent *string           `json:"display_agent,omitempty"`
	PaneID       string            `json:"pane_id"`
	StateLabels  map[string]string `json:"state_labels,omitempty"`
	Title        *string           `json:"title,omitempty"`
	Type         string            `json:"type"`
	WorkspaceID  string            `json:"workspace_id"`
}

// TagPaneAgentStatusChangedEvent is the EventData discriminator for PaneAgentStatusChangedEvent.
const TagPaneAgentStatusChangedEvent = "pane_agent_status_changed"

// LayoutUpdatedEvent is the "layout_updated" variant of EventData.
type LayoutUpdatedEvent struct {
	Layout PaneLayoutSnapshot `json:"layout"`
	Type   string             `json:"type"`
}

// TagLayoutUpdatedEvent is the EventData discriminator for LayoutUpdatedEvent.
const TagLayoutUpdatedEvent = "layout_updated"

type EventEnvelope struct {
	Data  EventData `json:"data"`
	Event EventKind `json:"event"`
}

type EventKind string

const (
	EventKindWorkspaceCreated         EventKind = "workspace_created"
	EventKindWorkspaceUpdated         EventKind = "workspace_updated"
	EventKindWorkspaceMetadataUpdated EventKind = "workspace_metadata_updated"
	EventKindWorkspaceClosed          EventKind = "workspace_closed"
	EventKindWorkspaceRenamed         EventKind = "workspace_renamed"
	EventKindWorkspaceMoved           EventKind = "workspace_moved"
	EventKindWorkspaceFocused         EventKind = "workspace_focused"
	EventKindWorktreeCreated          EventKind = "worktree_created"
	EventKindWorktreeOpened           EventKind = "worktree_opened"
	EventKindWorktreeRemoved          EventKind = "worktree_removed"
	EventKindTabCreated               EventKind = "tab_created"
	EventKindTabClosed                EventKind = "tab_closed"
	EventKindTabRenamed               EventKind = "tab_renamed"
	EventKindTabMoved                 EventKind = "tab_moved"
	EventKindTabFocused               EventKind = "tab_focused"
	EventKindPaneCreated              EventKind = "pane_created"
	EventKindPaneClosed               EventKind = "pane_closed"
	EventKindPaneUpdated              EventKind = "pane_updated"
	EventKindPaneFocused              EventKind = "pane_focused"
	EventKindPaneMoved                EventKind = "pane_moved"
	EventKindPaneOutputChanged        EventKind = "pane_output_changed"
	EventKindPaneExited               EventKind = "pane_exited"
	EventKindPaneAgentDetected        EventKind = "pane_agent_detected"
	EventKindPaneAgentStatusChanged   EventKind = "pane_agent_status_changed"
	EventKindLayoutUpdated            EventKind = "layout_updated"
)

type InstalledPluginInfo struct {
	Actions         []PluginManifestAction      `json:"actions,omitempty"`
	Build           []PluginManifestBuild       `json:"build,omitempty"`
	Description     *string                     `json:"description,omitempty"`
	Enabled         bool                        `json:"enabled"`
	Events          []PluginManifestEventHook   `json:"events,omitempty"`
	LinkHandlers    []PluginManifestLinkHandler `json:"link_handlers,omitempty"`
	ManifestPath    string                      `json:"manifest_path"`
	MinHerdrVersion *string                     `json:"min_herdr_version,omitempty"`
	Name            string                      `json:"name"`
	Panes           []PluginManifestPane        `json:"panes,omitempty"`
	Platforms       []PluginPlatform            `json:"platforms,omitempty"`
	PluginID        string                      `json:"plugin_id"`
	PluginRoot      string                      `json:"plugin_root"`
	Source          *PluginSourceInfo           `json:"source,omitempty"`
	Startup         []PluginManifestStartup     `json:"startup,omitempty"`
	Version         string                      `json:"version"`
	Warnings        []string                    `json:"warnings,omitempty"`
}

type IntegrationInstallResult struct {
	Messages []string `json:"messages"`
}

type IntegrationTarget string

const (
	IntegrationTargetPi         IntegrationTarget = "pi"
	IntegrationTargetOmp        IntegrationTarget = "omp"
	IntegrationTargetClaude     IntegrationTarget = "claude"
	IntegrationTargetCodex      IntegrationTarget = "codex"
	IntegrationTargetCopilot    IntegrationTarget = "copilot"
	IntegrationTargetDevin      IntegrationTarget = "devin"
	IntegrationTargetDroid      IntegrationTarget = "droid"
	IntegrationTargetKimi       IntegrationTarget = "kimi"
	IntegrationTargetOpencode   IntegrationTarget = "opencode"
	IntegrationTargetKilo       IntegrationTarget = "kilo"
	IntegrationTargetHermes     IntegrationTarget = "hermes"
	IntegrationTargetQodercli   IntegrationTarget = "qodercli"
	IntegrationTargetCursor     IntegrationTarget = "cursor"
	IntegrationTargetMastracode IntegrationTarget = "mastracode"
)

type IntegrationUninstallResult struct {
	Messages []string `json:"messages"`
}

type LayoutDescription struct {
	FocusedPaneID string     `json:"focused_pane_id"`
	Root          LayoutNode `json:"root"`
	TabID         string     `json:"tab_id"`
	WorkspaceID   string     `json:"workspace_id"`
	Zoomed        bool       `json:"zoomed"`
}

// LayoutNode is a tagged union; decode it into the matching variant.
type LayoutNode = json.RawMessage

// PaneLayoutNode is the "pane" variant of LayoutNode.
type PaneLayoutNode struct {
	Command []string          `json:"command,omitempty"`
	CWD     *string           `json:"cwd,omitempty"`
	Env     map[string]string `json:"env,omitempty"`
	Label   *string           `json:"label,omitempty"`
	PaneID  *string           `json:"pane_id,omitempty"`
	Type    string            `json:"type"`
}

// TagPaneLayoutNode is the LayoutNode discriminator for PaneLayoutNode.
const TagPaneLayoutNode = "pane"

// SplitLayoutNode is the "split" variant of LayoutNode.
type SplitLayoutNode struct {
	Direction SplitDirection `json:"direction"`
	First     LayoutNode     `json:"first"`
	Ratio     float64        `json:"ratio"`
	Second    LayoutNode     `json:"second"`
	Type      string         `json:"type"`
}

// TagSplitLayoutNode is the LayoutNode discriminator for SplitLayoutNode.
const TagSplitLayoutNode = "split"

type NotificationShowReason string

const (
	NotificationShowReasonShown              NotificationShowReason = "shown"
	NotificationShowReasonDisabled           NotificationShowReason = "disabled"
	NotificationShowReasonRateLimited        NotificationShowReason = "rate_limited"
	NotificationShowReasonNoForegroundClient NotificationShowReason = "no_foreground_client"
	NotificationShowReasonBusy               NotificationShowReason = "busy"
)

type PaneDirection string

const (
	PaneDirectionLeft  PaneDirection = "left"
	PaneDirectionRight PaneDirection = "right"
	PaneDirectionUp    PaneDirection = "up"
	PaneDirectionDown  PaneDirection = "down"
)

type PaneEdgesResult struct {
	Down   bool               `json:"down"`
	Layout PaneLayoutSnapshot `json:"layout"`
	Left   bool               `json:"left"`
	PaneID string             `json:"pane_id"`
	Right  bool               `json:"right"`
	Up     bool               `json:"up"`
}

type PaneFocusDirectionReason string

const (
	PaneFocusDirectionReasonNoNeighbor PaneFocusDirectionReason = "no_neighbor"
)

type PaneFocusDirectionResult struct {
	Changed       bool                      `json:"changed"`
	FocusedPaneID *string                   `json:"focused_pane_id,omitempty"`
	Layout        PaneLayoutSnapshot        `json:"layout"`
	Reason        *PaneFocusDirectionReason `json:"reason,omitempty"`
	SourcePaneID  string                    `json:"source_pane_id"`
}

type PaneInfo struct {
	Agent                 *string           `json:"agent,omitempty"`
	AgentSession          *AgentSessionInfo `json:"agent_session,omitempty"`
	AgentStatus           AgentStatus       `json:"agent_status"`
	CWD                   *string           `json:"cwd,omitempty"`
	DisplayAgent          *string           `json:"display_agent,omitempty"`
	Focused               bool              `json:"focused"`
	ForegroundCWD         *string           `json:"foreground_cwd,omitempty"`
	Label                 *string           `json:"label,omitempty"`
	PaneID                string            `json:"pane_id"`
	Revision              uint64            `json:"revision"`
	Scroll                *PaneScrollInfo   `json:"scroll,omitempty"`
	StateLabels           map[string]string `json:"state_labels,omitempty"`
	TabID                 string            `json:"tab_id"`
	TerminalID            string            `json:"terminal_id"`
	TerminalTitle         *string           `json:"terminal_title,omitempty"`
	TerminalTitleStripped *string           `json:"terminal_title_stripped,omitempty"`
	Title                 *string           `json:"title,omitempty"`
	Tokens                map[string]string `json:"tokens,omitempty"`
	WorkspaceID           string            `json:"workspace_id"`
}

type PaneLayoutPane struct {
	Focused bool           `json:"focused"`
	PaneID  string         `json:"pane_id"`
	Rect    PaneLayoutRect `json:"rect"`
}

type PaneLayoutRect struct {
	Height uint64 `json:"height"`
	Width  uint64 `json:"width"`
	X      uint64 `json:"x"`
	Y      uint64 `json:"y"`
}

type PaneLayoutSnapshot struct {
	Area          PaneLayoutRect    `json:"area"`
	FocusedPaneID string            `json:"focused_pane_id"`
	Panes         []PaneLayoutPane  `json:"panes"`
	Splits        []PaneLayoutSplit `json:"splits"`
	TabID         string            `json:"tab_id"`
	WorkspaceID   string            `json:"workspace_id"`
	Zoomed        bool              `json:"zoomed"`
}

type PaneLayoutSplit struct {
	Direction SplitDirection `json:"direction"`
	ID        string         `json:"id"`
	Ratio     float64        `json:"ratio"`
	Rect      PaneLayoutRect `json:"rect"`
}

type PaneMoveReason string

const (
	PaneMoveReasonSameTab   PaneMoveReason = "same_tab"
	PaneMoveReasonZoomedTab PaneMoveReason = "zoomed_tab"
)

type PaneMoveResult struct {
	Changed             bool                `json:"changed"`
	ClosedTabID         *string             `json:"closed_tab_id,omitempty"`
	ClosedWorkspaceID   *string             `json:"closed_workspace_id,omitempty"`
	CreatedTab          *TabInfo            `json:"created_tab,omitempty"`
	CreatedWorkspace    *WorkspaceInfo      `json:"created_workspace,omitempty"`
	FocusedPaneID       string              `json:"focused_pane_id"`
	Pane                PaneInfo            `json:"pane"`
	PreviousPaneID      string              `json:"previous_pane_id"`
	PreviousTabID       string              `json:"previous_tab_id"`
	PreviousWorkspaceID string              `json:"previous_workspace_id"`
	Reason              *PaneMoveReason     `json:"reason,omitempty"`
	SourceLayout        *PaneLayoutSnapshot `json:"source_layout,omitempty"`
	TargetLayout        PaneLayoutSnapshot  `json:"target_layout"`
}

type PaneNeighborResult struct {
	Direction      PaneDirection      `json:"direction"`
	Layout         PaneLayoutSnapshot `json:"layout"`
	NeighborPaneID *string            `json:"neighbor_pane_id,omitempty"`
	PaneID         string             `json:"pane_id"`
}

type PaneProcessInfo struct {
	ForegroundProcessGroupID *uint64                  `json:"foreground_process_group_id,omitempty"`
	ForegroundProcesses      []PaneProcessInfoProcess `json:"foreground_processes,omitempty"`
	PaneID                   string                   `json:"pane_id"`
	ShellPid                 *uint64                  `json:"shell_pid,omitempty"`
	Tty                      *string                  `json:"tty,omitempty"`
}

type PaneProcessInfoProcess struct {
	Argv    []string `json:"argv,omitempty"`
	Argv0   *string  `json:"argv0,omitempty"`
	Cmdline *string  `json:"cmdline,omitempty"`
	CWD     *string  `json:"cwd,omitempty"`
	Name    string   `json:"name"`
	Pid     uint64   `json:"pid"`
}

type PaneReadResult struct {
	Format      ReadFormat `json:"format"`
	PaneID      string     `json:"pane_id"`
	Revision    uint64     `json:"revision"`
	Source      ReadSource `json:"source"`
	TabID       string     `json:"tab_id"`
	Text        string     `json:"text"`
	Truncated   bool       `json:"truncated"`
	WorkspaceID string     `json:"workspace_id"`
}

type PaneResizeReason string

const (
	PaneResizeReasonUnchanged PaneResizeReason = "unchanged"
)

type PaneResizeResult struct {
	Changed       bool               `json:"changed"`
	FocusedPaneID string             `json:"focused_pane_id"`
	Layout        PaneLayoutSnapshot `json:"layout"`
	PaneID        string             `json:"pane_id"`
	Reason        *PaneResizeReason  `json:"reason,omitempty"`
}

type PaneScrollInfo struct {
	MaxOffsetFromBottom uint64 `json:"max_offset_from_bottom"`
	OffsetFromBottom    uint64 `json:"offset_from_bottom"`
	ViewportRows        uint64 `json:"viewport_rows"`
}

type PaneSwapReason string

const (
	PaneSwapReasonNoNeighbor PaneSwapReason = "no_neighbor"
	PaneSwapReasonSamePane   PaneSwapReason = "same_pane"
	PaneSwapReasonNotFound   PaneSwapReason = "not_found"
	PaneSwapReasonCrossTab   PaneSwapReason = "cross_tab"
)

type PaneSwapResult struct {
	Changed       bool               `json:"changed"`
	FocusedPaneID string             `json:"focused_pane_id"`
	Layout        PaneLayoutSnapshot `json:"layout"`
	Reason        *PaneSwapReason    `json:"reason,omitempty"`
	SourcePaneID  string             `json:"source_pane_id"`
	TargetPaneID  *string            `json:"target_pane_id,omitempty"`
}

type PaneZoomReason string

const (
	PaneZoomReasonSinglePane      PaneZoomReason = "single_pane"
	PaneZoomReasonAlreadyZoomed   PaneZoomReason = "already_zoomed"
	PaneZoomReasonAlreadyUnzoomed PaneZoomReason = "already_unzoomed"
)

type PaneZoomResult struct {
	Changed       bool               `json:"changed"`
	FocusChanged  bool               `json:"focus_changed"`
	FocusedPaneID string             `json:"focused_pane_id"`
	Layout        PaneLayoutSnapshot `json:"layout"`
	PaneID        string             `json:"pane_id"`
	Reason        *PaneZoomReason    `json:"reason,omitempty"`
	ZoomChanged   bool               `json:"zoom_changed"`
	Zoomed        bool               `json:"zoomed"`
}

type PluginActionContext string

const (
	PluginActionContextGlobal    PluginActionContext = "global"
	PluginActionContextWorkspace PluginActionContext = "workspace"
	PluginActionContextTab       PluginActionContext = "tab"
	PluginActionContextPane      PluginActionContext = "pane"
	PluginActionContextSelection PluginActionContext = "selection"
)

type PluginActionInfo struct {
	ActionID    string                `json:"action_id"`
	Command     []string              `json:"command"`
	Contexts    []PluginActionContext `json:"contexts,omitempty"`
	Description *string               `json:"description,omitempty"`
	Platforms   []PluginPlatform      `json:"platforms,omitempty"`
	PluginID    string                `json:"plugin_id"`
	Title       string                `json:"title"`
}

type PluginCommandLogInfo struct {
	ActionID       *string             `json:"action_id,omitempty"`
	Command        []string            `json:"command"`
	Error          *string             `json:"error,omitempty"`
	Event          *string             `json:"event,omitempty"`
	ExitCode       *int64              `json:"exit_code,omitempty"`
	FinishedUnixMs *uint64             `json:"finished_unix_ms,omitempty"`
	LogID          string              `json:"log_id"`
	PluginID       string              `json:"plugin_id"`
	StartedUnixMs  uint64              `json:"started_unix_ms"`
	Status         PluginCommandStatus `json:"status"`
	Stderr         *string             `json:"stderr,omitempty"`
	Stdout         *string             `json:"stdout,omitempty"`
}

type PluginCommandStatus string

const (
	PluginCommandStatusRunning   PluginCommandStatus = "running"
	PluginCommandStatusSucceeded PluginCommandStatus = "succeeded"
	PluginCommandStatusFailed    PluginCommandStatus = "failed"
)

type PluginInvocationContext struct {
	ClickedURL        *string                `json:"clicked_url,omitempty"`
	CorrelationID     *string                `json:"correlation_id,omitempty"`
	FocusedPaneAgent  *string                `json:"focused_pane_agent,omitempty"`
	FocusedPaneCWD    *string                `json:"focused_pane_cwd,omitempty"`
	FocusedPaneID     *string                `json:"focused_pane_id,omitempty"`
	FocusedPaneStatus *AgentStatus           `json:"focused_pane_status,omitempty"`
	InvocationSource  *string                `json:"invocation_source,omitempty"`
	LinkHandlerID     *string                `json:"link_handler_id,omitempty"`
	SelectedText      *string                `json:"selected_text,omitempty"`
	TabID             *string                `json:"tab_id,omitempty"`
	TabLabel          *string                `json:"tab_label,omitempty"`
	WorkspaceCWD      *string                `json:"workspace_cwd,omitempty"`
	WorkspaceID       *string                `json:"workspace_id,omitempty"`
	WorkspaceLabel    *string                `json:"workspace_label,omitempty"`
	Worktree          *WorkspaceWorktreeInfo `json:"worktree,omitempty"`
}

type PluginManifestAction struct {
	Command     []string              `json:"command"`
	Contexts    []PluginActionContext `json:"contexts,omitempty"`
	Description *string               `json:"description,omitempty"`
	ID          string                `json:"id"`
	Platforms   []PluginPlatform      `json:"platforms,omitempty"`
	Title       string                `json:"title"`
}

type PluginManifestBuild struct {
	Command   []string         `json:"command"`
	Platforms []PluginPlatform `json:"platforms,omitempty"`
}

type PluginManifestEventHook struct {
	Command   []string         `json:"command"`
	On        string           `json:"on"`
	Platforms []PluginPlatform `json:"platforms,omitempty"`
}

type PluginManifestLinkHandler struct {
	Action    string           `json:"action"`
	ID        string           `json:"id"`
	Pattern   string           `json:"pattern"`
	Platforms []PluginPlatform `json:"platforms,omitempty"`
	Title     string           `json:"title"`
}

type PluginManifestPane struct {
	Command     []string             `json:"command"`
	Description *string              `json:"description,omitempty"`
	Height      *PopupSize           `json:"height,omitempty"`
	ID          string               `json:"id"`
	Placement   *PluginPanePlacement `json:"placement,omitempty"`
	Platforms   []PluginPlatform     `json:"platforms,omitempty"`
	Title       string               `json:"title"`
	Width       *PopupSize           `json:"width,omitempty"`
}

type PluginManifestStartup struct {
	Command   []string         `json:"command"`
	Platforms []PluginPlatform `json:"platforms,omitempty"`
}

type PluginPaneInfo struct {
	Entrypoint string   `json:"entrypoint"`
	Pane       PaneInfo `json:"pane"`
	PluginID   string   `json:"plugin_id"`
}

type PluginPanePlacement string

const (
	PluginPanePlacementOverlay PluginPanePlacement = "overlay"
	PluginPanePlacementPopup   PluginPanePlacement = "popup"
	PluginPanePlacementSplit   PluginPanePlacement = "split"
	PluginPanePlacementTab     PluginPanePlacement = "tab"
	PluginPanePlacementZoomed  PluginPanePlacement = "zoomed"
)

type PluginPlatform string

const (
	PluginPlatformLinux   PluginPlatform = "linux"
	PluginPlatformMacos   PluginPlatform = "macos"
	PluginPlatformWindows PluginPlatform = "windows"
)

type PluginSourceInfo struct {
	InstalledUnixMs *uint64           `json:"installed_unix_ms,omitempty"`
	Kind            *PluginSourceKind `json:"kind,omitempty"`
	ManagedPath     *string           `json:"managed_path,omitempty"`
	Owner           *string           `json:"owner,omitempty"`
	Repo            *string           `json:"repo,omitempty"`
	RequestedRef    *string           `json:"requested_ref,omitempty"`
	ResolvedCommit  *string           `json:"resolved_commit,omitempty"`
	Subdir          *string           `json:"subdir,omitempty"`
}

type PluginSourceKind string

const (
	PluginSourceKindLocal  PluginSourceKind = "local"
	PluginSourceKindGithub PluginSourceKind = "github"
)

// PopupSize is a tagged union; decode it into the matching variant.
type PopupSize = json.RawMessage

type ReadFormat string

const (
	ReadFormatText ReadFormat = "text"
	ReadFormatAnsi ReadFormat = "ansi"
)

type ReadSource string

const (
	ReadSourceVisible         ReadSource = "visible"
	ReadSourceRecent          ReadSource = "recent"
	ReadSourceRecentUnwrapped ReadSource = "recent_unwrapped"
	ReadSourceDetection       ReadSource = "detection"
)

// ResponseResult is a tagged union; decode it into the matching variant.
type ResponseResult = json.RawMessage

// PongResponse is the "pong" variant of ResponseResult.
type PongResponse struct {
	Capabilities *ServerCapabilities `json:"capabilities,omitempty"`
	Protocol     uint64              `json:"protocol"`
	Type         string              `json:"type"`
	Version      string              `json:"version"`
}

// TagPongResponse is the ResponseResult discriminator for PongResponse.
const TagPongResponse = "pong"

// SessionSnapshotResponse is the "session_snapshot" variant of ResponseResult.
type SessionSnapshotResponse struct {
	Snapshot SessionSnapshot `json:"snapshot"`
	Type     string          `json:"type"`
}

// TagSessionSnapshotResponse is the ResponseResult discriminator for SessionSnapshotResponse.
const TagSessionSnapshotResponse = "session_snapshot"

// WorkspaceInfoResponse is the "workspace_info" variant of ResponseResult.
type WorkspaceInfoResponse struct {
	Type      string        `json:"type"`
	Workspace WorkspaceInfo `json:"workspace"`
}

// TagWorkspaceInfoResponse is the ResponseResult discriminator for WorkspaceInfoResponse.
const TagWorkspaceInfoResponse = "workspace_info"

// WorkspaceCreatedResponse is the "workspace_created" variant of ResponseResult.
type WorkspaceCreatedResponse struct {
	RootPane  PaneInfo      `json:"root_pane"`
	Tab       TabInfo       `json:"tab"`
	Type      string        `json:"type"`
	Workspace WorkspaceInfo `json:"workspace"`
}

// TagWorkspaceCreatedResponse is the ResponseResult discriminator for WorkspaceCreatedResponse.
const TagWorkspaceCreatedResponse = "workspace_created"

// WorkspaceListResponse is the "workspace_list" variant of ResponseResult.
type WorkspaceListResponse struct {
	Type       string          `json:"type"`
	Workspaces []WorkspaceInfo `json:"workspaces"`
}

// TagWorkspaceListResponse is the ResponseResult discriminator for WorkspaceListResponse.
const TagWorkspaceListResponse = "workspace_list"

// WorktreeListResponse is the "worktree_list" variant of ResponseResult.
type WorktreeListResponse struct {
	Source    WorktreeSourceInfo `json:"source"`
	Type      string             `json:"type"`
	Worktrees []WorktreeInfo     `json:"worktrees"`
}

// TagWorktreeListResponse is the ResponseResult discriminator for WorktreeListResponse.
const TagWorktreeListResponse = "worktree_list"

// WorktreeCreatedResponse is the "worktree_created" variant of ResponseResult.
type WorktreeCreatedResponse struct {
	RootPane  PaneInfo      `json:"root_pane"`
	Tab       TabInfo       `json:"tab"`
	Type      string        `json:"type"`
	Workspace WorkspaceInfo `json:"workspace"`
	Worktree  WorktreeInfo  `json:"worktree"`
}

// TagWorktreeCreatedResponse is the ResponseResult discriminator for WorktreeCreatedResponse.
const TagWorktreeCreatedResponse = "worktree_created"

// WorktreeOpenedResponse is the "worktree_opened" variant of ResponseResult.
type WorktreeOpenedResponse struct {
	AlreadyOpen bool          `json:"already_open"`
	RootPane    PaneInfo      `json:"root_pane"`
	Tab         TabInfo       `json:"tab"`
	Type        string        `json:"type"`
	Workspace   WorkspaceInfo `json:"workspace"`
	Worktree    WorktreeInfo  `json:"worktree"`
}

// TagWorktreeOpenedResponse is the ResponseResult discriminator for WorktreeOpenedResponse.
const TagWorktreeOpenedResponse = "worktree_opened"

// WorktreeRemovedResponse is the "worktree_removed" variant of ResponseResult.
type WorktreeRemovedResponse struct {
	Forced      bool   `json:"forced"`
	Path        string `json:"path"`
	Type        string `json:"type"`
	WorkspaceID string `json:"workspace_id"`
}

// TagWorktreeRemovedResponse is the ResponseResult discriminator for WorktreeRemovedResponse.
const TagWorktreeRemovedResponse = "worktree_removed"

// TabInfoResponse is the "tab_info" variant of ResponseResult.
type TabInfoResponse struct {
	Tab  TabInfo `json:"tab"`
	Type string  `json:"type"`
}

// TagTabInfoResponse is the ResponseResult discriminator for TabInfoResponse.
const TagTabInfoResponse = "tab_info"

// TabCreatedResponse is the "tab_created" variant of ResponseResult.
type TabCreatedResponse struct {
	RootPane PaneInfo `json:"root_pane"`
	Tab      TabInfo  `json:"tab"`
	Type     string   `json:"type"`
}

// TagTabCreatedResponse is the ResponseResult discriminator for TabCreatedResponse.
const TagTabCreatedResponse = "tab_created"

// TabListResponse is the "tab_list" variant of ResponseResult.
type TabListResponse struct {
	Tabs []TabInfo `json:"tabs"`
	Type string    `json:"type"`
}

// TagTabListResponse is the ResponseResult discriminator for TabListResponse.
const TagTabListResponse = "tab_list"

// AgentInfoResponse is the "agent_info" variant of ResponseResult.
type AgentInfoResponse struct {
	Agent AgentInfo `json:"agent"`
	Type  string    `json:"type"`
}

// TagAgentInfoResponse is the ResponseResult discriminator for AgentInfoResponse.
const TagAgentInfoResponse = "agent_info"

// AgentStartedResponse is the "agent_started" variant of ResponseResult.
type AgentStartedResponse struct {
	Agent AgentInfo `json:"agent"`
	Argv  []string  `json:"argv"`
	Type  string    `json:"type"`
}

// TagAgentStartedResponse is the ResponseResult discriminator for AgentStartedResponse.
const TagAgentStartedResponse = "agent_started"

// AgentPromptedResponse is the "agent_prompted" variant of ResponseResult.
type AgentPromptedResponse struct {
	Agent AgentInfo `json:"agent"`
	Type  string    `json:"type"`
}

// TagAgentPromptedResponse is the ResponseResult discriminator for AgentPromptedResponse.
const TagAgentPromptedResponse = "agent_prompted"

// AgentListResponse is the "agent_list" variant of ResponseResult.
type AgentListResponse struct {
	Agents []AgentInfo `json:"agents"`
	Type   string      `json:"type"`
}

// TagAgentListResponse is the ResponseResult discriminator for AgentListResponse.
const TagAgentListResponse = "agent_list"

// AgentViewResponse is the "agent_view" variant of ResponseResult.
type AgentViewResponse struct {
	Active bool    `json:"active"`
	Label  *string `json:"label,omitempty"`
	Source *string `json:"source,omitempty"`
	Type   string  `json:"type"`
}

// TagAgentViewResponse is the ResponseResult discriminator for AgentViewResponse.
const TagAgentViewResponse = "agent_view"

// PaneInfoResponse is the "pane_info" variant of ResponseResult.
type PaneInfoResponse struct {
	Pane PaneInfo `json:"pane"`
	Type string   `json:"type"`
}

// TagPaneInfoResponse is the ResponseResult discriminator for PaneInfoResponse.
const TagPaneInfoResponse = "pane_info"

// PaneListResponse is the "pane_list" variant of ResponseResult.
type PaneListResponse struct {
	Panes []PaneInfo `json:"panes"`
	Type  string     `json:"type"`
}

// TagPaneListResponse is the ResponseResult discriminator for PaneListResponse.
const TagPaneListResponse = "pane_list"

// PaneCurrentResponse is the "pane_current" variant of ResponseResult.
type PaneCurrentResponse struct {
	Pane PaneInfo `json:"pane"`
	Type string   `json:"type"`
}

// TagPaneCurrentResponse is the ResponseResult discriminator for PaneCurrentResponse.
const TagPaneCurrentResponse = "pane_current"

// PaneSwapResponse is the "pane_swap" variant of ResponseResult.
type PaneSwapResponse struct {
	Swap PaneSwapResult `json:"swap"`
	Type string         `json:"type"`
}

// TagPaneSwapResponse is the ResponseResult discriminator for PaneSwapResponse.
const TagPaneSwapResponse = "pane_swap"

// PaneMoveResponse is the "pane_move" variant of ResponseResult.
type PaneMoveResponse struct {
	MoveResult PaneMoveResult `json:"move_result"`
	Type       string         `json:"type"`
}

// TagPaneMoveResponse is the ResponseResult discriminator for PaneMoveResponse.
const TagPaneMoveResponse = "pane_move"

// PaneZoomResponse is the "pane_zoom" variant of ResponseResult.
type PaneZoomResponse struct {
	Type string         `json:"type"`
	Zoom PaneZoomResult `json:"zoom"`
}

// TagPaneZoomResponse is the ResponseResult discriminator for PaneZoomResponse.
const TagPaneZoomResponse = "pane_zoom"

// PaneLayoutResponse is the "pane_layout" variant of ResponseResult.
type PaneLayoutResponse struct {
	Layout PaneLayoutSnapshot `json:"layout"`
	Type   string             `json:"type"`
}

// TagPaneLayoutResponse is the ResponseResult discriminator for PaneLayoutResponse.
const TagPaneLayoutResponse = "pane_layout"

// PaneProcessInfoResponse is the "pane_process_info" variant of ResponseResult.
type PaneProcessInfoResponse struct {
	ProcessInfo PaneProcessInfo `json:"process_info"`
	Type        string          `json:"type"`
}

// TagPaneProcessInfoResponse is the ResponseResult discriminator for PaneProcessInfoResponse.
const TagPaneProcessInfoResponse = "pane_process_info"

// LayoutExportResponse is the "layout_export" variant of ResponseResult.
type LayoutExportResponse struct {
	Layout LayoutDescription `json:"layout"`
	Type   string            `json:"type"`
}

// TagLayoutExportResponse is the ResponseResult discriminator for LayoutExportResponse.
const TagLayoutExportResponse = "layout_export"

// LayoutApplyResponse is the "layout_apply" variant of ResponseResult.
type LayoutApplyResponse struct {
	Layout LayoutDescription `json:"layout"`
	Type   string            `json:"type"`
}

// TagLayoutApplyResponse is the ResponseResult discriminator for LayoutApplyResponse.
const TagLayoutApplyResponse = "layout_apply"

// LayoutSplitRatioSetResponse is the "layout_split_ratio_set" variant of ResponseResult.
type LayoutSplitRatioSetResponse struct {
	Layout LayoutDescription `json:"layout"`
	Type   string            `json:"type"`
}

// TagLayoutSplitRatioSetResponse is the ResponseResult discriminator for LayoutSplitRatioSetResponse.
const TagLayoutSplitRatioSetResponse = "layout_split_ratio_set"

// PaneNeighborResponse is the "pane_neighbor" variant of ResponseResult.
type PaneNeighborResponse struct {
	Neighbor PaneNeighborResult `json:"neighbor"`
	Type     string             `json:"type"`
}

// TagPaneNeighborResponse is the ResponseResult discriminator for PaneNeighborResponse.
const TagPaneNeighborResponse = "pane_neighbor"

// PaneEdgesResponse is the "pane_edges" variant of ResponseResult.
type PaneEdgesResponse struct {
	Edges PaneEdgesResult `json:"edges"`
	Type  string          `json:"type"`
}

// TagPaneEdgesResponse is the ResponseResult discriminator for PaneEdgesResponse.
const TagPaneEdgesResponse = "pane_edges"

// PaneFocusDirectionResponse is the "pane_focus_direction" variant of ResponseResult.
type PaneFocusDirectionResponse struct {
	Focus PaneFocusDirectionResult `json:"focus"`
	Type  string                   `json:"type"`
}

// TagPaneFocusDirectionResponse is the ResponseResult discriminator for PaneFocusDirectionResponse.
const TagPaneFocusDirectionResponse = "pane_focus_direction"

// PaneResizeResponse is the "pane_resize" variant of ResponseResult.
type PaneResizeResponse struct {
	Resize PaneResizeResult `json:"resize"`
	Type   string           `json:"type"`
}

// TagPaneResizeResponse is the ResponseResult discriminator for PaneResizeResponse.
const TagPaneResizeResponse = "pane_resize"

// PaneReadResponse is the "pane_read" variant of ResponseResult.
type PaneReadResponse struct {
	Read PaneReadResult `json:"read"`
	Type string         `json:"type"`
}

// TagPaneReadResponse is the ResponseResult discriminator for PaneReadResponse.
const TagPaneReadResponse = "pane_read"

// PaneGraphicsInfoResponse is the "pane_graphics_info" variant of ResponseResult.
type PaneGraphicsInfoResponse struct {
	CellHeightPx uint64 `json:"cell_height_px"`
	CellWidthPx  uint64 `json:"cell_width_px"`
	Type         string `json:"type"`
}

// TagPaneGraphicsInfoResponse is the ResponseResult discriminator for PaneGraphicsInfoResponse.
const TagPaneGraphicsInfoResponse = "pane_graphics_info"

// AgentExplainResponse is the "agent_explain" variant of ResponseResult.
type AgentExplainResponse struct {
	Explain any    `json:"explain"`
	Type    string `json:"type"`
}

// TagAgentExplainResponse is the ResponseResult discriminator for AgentExplainResponse.
const TagAgentExplainResponse = "agent_explain"

// SubscriptionStartedResponse is the "subscription_started" variant of ResponseResult.
type SubscriptionStartedResponse struct {
	Type string `json:"type"`
}

// TagSubscriptionStartedResponse is the ResponseResult discriminator for SubscriptionStartedResponse.
const TagSubscriptionStartedResponse = "subscription_started"

// WaitMatchedResponse is the "wait_matched" variant of ResponseResult.
type WaitMatchedResponse struct {
	Event EventEnvelope `json:"event"`
	Type  string        `json:"type"`
}

// TagWaitMatchedResponse is the ResponseResult discriminator for WaitMatchedResponse.
const TagWaitMatchedResponse = "wait_matched"

// OutputMatchedResponse is the "output_matched" variant of ResponseResult.
type OutputMatchedResponse struct {
	MatchedLine *string        `json:"matched_line,omitempty"`
	PaneID      string         `json:"pane_id"`
	Read        PaneReadResult `json:"read"`
	Revision    uint64         `json:"revision"`
	Type        string         `json:"type"`
}

// TagOutputMatchedResponse is the ResponseResult discriminator for OutputMatchedResponse.
const TagOutputMatchedResponse = "output_matched"

// NotificationShowResponse is the "notification_show" variant of ResponseResult.
type NotificationShowResponse struct {
	Reason NotificationShowReason `json:"reason"`
	Shown  bool                   `json:"shown"`
	Type   string                 `json:"type"`
}

// TagNotificationShowResponse is the ResponseResult discriminator for NotificationShowResponse.
const TagNotificationShowResponse = "notification_show"

// ClientWindowTitleResponse is the "client_window_title" variant of ResponseResult.
type ClientWindowTitleResponse struct {
	Changed bool                    `json:"changed"`
	Reason  ClientWindowTitleReason `json:"reason"`
	Type    string                  `json:"type"`
}

// TagClientWindowTitleResponse is the ResponseResult discriminator for ClientWindowTitleResponse.
const TagClientWindowTitleResponse = "client_window_title"

// IntegrationInstallResponse is the "integration_install" variant of ResponseResult.
type IntegrationInstallResponse struct {
	Details IntegrationInstallResult `json:"details"`
	Target  IntegrationTarget        `json:"target"`
	Type    string                   `json:"type"`
}

// TagIntegrationInstallResponse is the ResponseResult discriminator for IntegrationInstallResponse.
const TagIntegrationInstallResponse = "integration_install"

// IntegrationUninstallResponse is the "integration_uninstall" variant of ResponseResult.
type IntegrationUninstallResponse struct {
	Details IntegrationUninstallResult `json:"details"`
	Target  IntegrationTarget          `json:"target"`
	Type    string                     `json:"type"`
}

// TagIntegrationUninstallResponse is the ResponseResult discriminator for IntegrationUninstallResponse.
const TagIntegrationUninstallResponse = "integration_uninstall"

// AgentManifestReloadResponse is the "agent_manifest_reload" variant of ResponseResult.
type AgentManifestReloadResponse struct {
	Manifests []AgentManifestInfo `json:"manifests"`
	Type      string              `json:"type"`
}

// TagAgentManifestReloadResponse is the ResponseResult discriminator for AgentManifestReloadResponse.
const TagAgentManifestReloadResponse = "agent_manifest_reload"

// AgentManifestStatusResponse is the "agent_manifest_status" variant of ResponseResult.
type AgentManifestStatusResponse struct {
	LastCheckUnix *uint64             `json:"last_check_unix,omitempty"`
	LastResult    *string             `json:"last_result,omitempty"`
	Manifests     []AgentManifestInfo `json:"manifests"`
	Type          string              `json:"type"`
}

// TagAgentManifestStatusResponse is the ResponseResult discriminator for AgentManifestStatusResponse.
const TagAgentManifestStatusResponse = "agent_manifest_status"

// PluginLinkedResponse is the "plugin_linked" variant of ResponseResult.
type PluginLinkedResponse struct {
	Plugin InstalledPluginInfo `json:"plugin"`
	Type   string              `json:"type"`
}

// TagPluginLinkedResponse is the ResponseResult discriminator for PluginLinkedResponse.
const TagPluginLinkedResponse = "plugin_linked"

// PluginListResponse is the "plugin_list" variant of ResponseResult.
type PluginListResponse struct {
	Plugins []InstalledPluginInfo `json:"plugins"`
	Type    string                `json:"type"`
}

// TagPluginListResponse is the ResponseResult discriminator for PluginListResponse.
const TagPluginListResponse = "plugin_list"

// PluginUnlinkedResponse is the "plugin_unlinked" variant of ResponseResult.
type PluginUnlinkedResponse struct {
	PluginID string `json:"plugin_id"`
	Removed  bool   `json:"removed"`
	Type     string `json:"type"`
}

// TagPluginUnlinkedResponse is the ResponseResult discriminator for PluginUnlinkedResponse.
const TagPluginUnlinkedResponse = "plugin_unlinked"

// PluginEnabledResponse is the "plugin_enabled" variant of ResponseResult.
type PluginEnabledResponse struct {
	Plugin InstalledPluginInfo `json:"plugin"`
	Type   string              `json:"type"`
}

// TagPluginEnabledResponse is the ResponseResult discriminator for PluginEnabledResponse.
const TagPluginEnabledResponse = "plugin_enabled"

// PluginDisabledResponse is the "plugin_disabled" variant of ResponseResult.
type PluginDisabledResponse struct {
	Plugin InstalledPluginInfo `json:"plugin"`
	Type   string              `json:"type"`
}

// TagPluginDisabledResponse is the ResponseResult discriminator for PluginDisabledResponse.
const TagPluginDisabledResponse = "plugin_disabled"

// PluginActionListResponse is the "plugin_action_list" variant of ResponseResult.
type PluginActionListResponse struct {
	Actions []PluginActionInfo `json:"actions"`
	Type    string             `json:"type"`
}

// TagPluginActionListResponse is the ResponseResult discriminator for PluginActionListResponse.
const TagPluginActionListResponse = "plugin_action_list"

// PluginActionInvokedResponse is the "plugin_action_invoked" variant of ResponseResult.
type PluginActionInvokedResponse struct {
	Action  PluginActionInfo        `json:"action"`
	Context PluginInvocationContext `json:"context"`
	Log     PluginCommandLogInfo    `json:"log"`
	Type    string                  `json:"type"`
}

// TagPluginActionInvokedResponse is the ResponseResult discriminator for PluginActionInvokedResponse.
const TagPluginActionInvokedResponse = "plugin_action_invoked"

// PluginLogListResponse is the "plugin_log_list" variant of ResponseResult.
type PluginLogListResponse struct {
	Logs []PluginCommandLogInfo `json:"logs"`
	Type string                 `json:"type"`
}

// TagPluginLogListResponse is the ResponseResult discriminator for PluginLogListResponse.
const TagPluginLogListResponse = "plugin_log_list"

// PluginPaneOpenedResponse is the "plugin_pane_opened" variant of ResponseResult.
type PluginPaneOpenedResponse struct {
	PluginPane PluginPaneInfo `json:"plugin_pane"`
	Type       string         `json:"type"`
}

// TagPluginPaneOpenedResponse is the ResponseResult discriminator for PluginPaneOpenedResponse.
const TagPluginPaneOpenedResponse = "plugin_pane_opened"

// PluginPaneFocusedResponse is the "plugin_pane_focused" variant of ResponseResult.
type PluginPaneFocusedResponse struct {
	PluginPane PluginPaneInfo `json:"plugin_pane"`
	Type       string         `json:"type"`
}

// TagPluginPaneFocusedResponse is the ResponseResult discriminator for PluginPaneFocusedResponse.
const TagPluginPaneFocusedResponse = "plugin_pane_focused"

// PluginPaneClosedResponse is the "plugin_pane_closed" variant of ResponseResult.
type PluginPaneClosedResponse struct {
	PaneID string `json:"pane_id"`
	Type   string `json:"type"`
}

// TagPluginPaneClosedResponse is the ResponseResult discriminator for PluginPaneClosedResponse.
const TagPluginPaneClosedResponse = "plugin_pane_closed"

// ConfigReloadResponse is the "config_reload" variant of ResponseResult.
type ConfigReloadResponse struct {
	Diagnostics []string           `json:"diagnostics"`
	Status      ConfigReloadStatus `json:"status"`
	Type        string             `json:"type"`
}

// TagConfigReloadResponse is the ResponseResult discriminator for ConfigReloadResponse.
const TagConfigReloadResponse = "config_reload"

// OkResponse is the "ok" variant of ResponseResult.
type OkResponse struct {
	Type string `json:"type"`
}

// TagOkResponse is the ResponseResult discriminator for OkResponse.
const TagOkResponse = "ok"

type ServerCapabilities struct {
	DetachedServerDaemon *bool `json:"detached_server_daemon,omitempty"`
	LiveHandoff          bool  `json:"live_handoff"`
}

type SessionSnapshot struct {
	Agents             []AgentInfo          `json:"agents"`
	FocusedPaneID      *string              `json:"focused_pane_id,omitempty"`
	FocusedTabID       *string              `json:"focused_tab_id,omitempty"`
	FocusedWorkspaceID *string              `json:"focused_workspace_id,omitempty"`
	Layouts            []PaneLayoutSnapshot `json:"layouts"`
	Panes              []PaneInfo           `json:"panes"`
	Protocol           uint64               `json:"protocol"`
	Tabs               []TabInfo            `json:"tabs"`
	Version            string               `json:"version"`
	Workspaces         []WorkspaceInfo      `json:"workspaces"`
}

type SplitDirection string

const (
	SplitDirectionRight SplitDirection = "right"
	SplitDirectionDown  SplitDirection = "down"
)

type TabInfo struct {
	AgentStatus AgentStatus `json:"agent_status"`
	Focused     bool        `json:"focused"`
	Label       string      `json:"label"`
	Number      uint64      `json:"number"`
	PaneCount   uint64      `json:"pane_count"`
	TabID       string      `json:"tab_id"`
	WorkspaceID string      `json:"workspace_id"`
}

type WorkspaceInfo struct {
	ActiveTabID string                 `json:"active_tab_id"`
	AgentStatus AgentStatus            `json:"agent_status"`
	Focused     bool                   `json:"focused"`
	Label       string                 `json:"label"`
	Number      uint64                 `json:"number"`
	PaneCount   uint64                 `json:"pane_count"`
	TabCount    uint64                 `json:"tab_count"`
	Tokens      map[string]string      `json:"tokens,omitempty"`
	WorkspaceID string                 `json:"workspace_id"`
	Worktree    *WorkspaceWorktreeInfo `json:"worktree,omitempty"`
}

type WorkspaceWorktreeInfo struct {
	CheckoutPath     string `json:"checkout_path"`
	IsLinkedWorktree bool   `json:"is_linked_worktree"`
	RepoKey          string `json:"repo_key"`
	RepoName         string `json:"repo_name"`
	RepoRoot         string `json:"repo_root"`
}

type WorktreeInfo struct {
	Branch           *string `json:"branch,omitempty"`
	IsBare           bool    `json:"is_bare"`
	IsDetached       bool    `json:"is_detached"`
	IsLinkedWorktree bool    `json:"is_linked_worktree"`
	IsPrunable       bool    `json:"is_prunable"`
	Label            string  `json:"label"`
	OpenWorkspaceID  *string `json:"open_workspace_id,omitempty"`
	Path             string  `json:"path"`
}

type WorktreeSourceInfo struct {
	RepoKey            string  `json:"repo_key"`
	RepoName           string  `json:"repo_name"`
	RepoRoot           string  `json:"repo_root"`
	SourceCheckoutPath string  `json:"source_checkout_path"`
	SourceWorkspaceID  *string `json:"source_workspace_id,omitempty"`
}
